### ISSUE TITLE
Reconsider `range` and `range'`

### ISSUE THREAD

**Issue by thought2** [bodil/purescript-sized-vectors#22]
## `Vec.range` vs `Unfoldable.range`

It's obvious that we cannot have an `Unfoldable` instance. However, I found it confusing once that `Vec.range` and `Vec.range'` behave differently from `Unfoldable.range` and e.g. `Array.range`.

- The common `range` functions include both endpoints and they don't have to be in the 'min, max' order. e.g. `range 2 (-1)` is `[2, 1, 0, -1]`

- In this library `range` only counts up and the second argument (either given in `range` or implicitly given in `range'`) is not the second endpoint but the size. If you misinterpret it as an endpoint (which happend to me and lead to an evil bug :) ) you'll wonder why it's not included.

Couldn't we express the existing range just with `fill` (as its implementation) and thus maybe drop it?

## A different `range`

and here's a suggestion of how a `range` could be closer to the 'real' one:

```
rangeNew ::
  forall n1 n2 n3 max min diff.
  Nat n1 =>
  Nat n2 =>
  Max n1 n2 max =>
  Min n1 n2 min =>
  Sub max min diff =>
  Pos diff =>
  Succ diff n3 =>
  n1 -> n2 -> Vec n3 Int
rangeNew _ _ = Vec $ Array.range (toInt (undefined :: n1)) (toInt (undefined :: n2))
```

This follows the same laws as the known `range`, it only adds a typelevel restriction: No negative endpoints, and they cannot be equal.

```
rangeNew d2 d2 -- compile error
rangeNew d4 d2 -- 4 +> 3 +> 2 +> empty
rangeNew d2 d4 -- 2 +> 3 +> 4 +> empty
```

**Comment by 3ddyy** [comment]
Good idea. The range function confused me as well when i first saw it

**Comment by 3ddyy** [comment]
Why should `rangeNew d2 d2` error? Why not just remove the `Pos diff` constraint and allow it to create empty vecs?

Also, i believe it's more common to format type signatures with operators first on the line, like this:
```
rangeNew
  :: forall n1 n2 n3 max min diff
   . Nat n1
  => Nat n2
  => Max n1 n2 max
  => Min n1 n2 min
  => Sub max min diff
  => Succ diff n3
  => n1 -> n2 -> Vec n3 Int
```

**Comment by thought2** [comment]
Yes true, we can omit the `Pos`. That's better. It will not create empty vecs, but singleton ones.
`rangeNew d2 d2 -- 2 +> empty`

Regarding the formatting. I use `purty`. It's not perfect but pretty good.

**Comment by 3ddyy** [comment]
right, i misthought

**Comment by athanclark** [comment]
Wow this is a really good idea, good work!
