### ISSUE TITLE
Add `FunctorWithIndex` instance

### ISSUE THREAD

**Issue by thought2** [bodil/purescript-sized-vectors#23]
To me it looks like this should be good to have.

**Comment by 3ddyy** [comment]
Also `FoldableWithIndex` and `TraversableWithIndex`

**Comment by thought2** [comment]
Working on this: https://github.com/thought2/purescript-sized-vectors/tree/feature/with-index-instances

**Comment by athanclark** [comment]
Merged, thank you!
