### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by thought2** [bodil/purescript-sized-vectors#25]
We could use `purty` as a code formatter. What do you think?

Check e.g.:
https://github.com/bodil/purescript-sized-vectors/blob/master/src/Data/Vec.purs#L216

Code formatting could even get enforced by CI.

**Comment by athanclark** [comment]
Oddly I'm not getting a different format, or at least not a drastically different one, when running `purty` on the code. But I don't think it would be a bad idea - see if `purty` is idempotent

**Comment by athanclark** [comment]
Now integrated as of https://github.com/bodil/purescript-sized-vectors/commit/1bb96ae8893d20cd21e4217ca2bb90d67eb8c4cc
