### ISSUE TITLE
Swap all uses of `toInt (undefined :: s)` to `toInt' (Proxy :: Proxy s)`

### ISSUE THREAD

**Issue by athanclark** [bodil/purescript-sized-vectors#28]
It would just make me feel better

**Comment by 3ddyy** [comment]
why are you adding the invalid label?

**Comment by athanclark** [comment]
"invalid" in the sense of "the current code is invalid" - this issue doesn't declare a bug, but rather declares that the code isn't valid. There isn't an issue with the behavior, but rather the design.
